version: '3'

services:
  tomcat:
    build:
     context: ./

    ports:
    - 8080:8080
    volumes:
    - ./webapps/sample:/usr/local/tomcat/webapps/sample
    - ./webapps/sample2:/usr/local/tomcat/webbackend/sample2
    - ./build/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
